//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.IndicatorsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndicatorsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicatorsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.IndicatorsResources.IndicatorsPage", typeof(IndicatorsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComponentFormButtonCancel {
            get {
                return ResourceManager.GetString("ComponentFormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ComponentFormButtonCreate {
            get {
                return ResourceManager.GetString("ComponentFormButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ComponentFormButtonUpdate {
            get {
                return ResourceManager.GetString("ComponentFormButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Indicator.
        /// </summary>
        public static string ComponentFormCreateTitle {
            get {
                return ResourceManager.GetString("ComponentFormCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ComponentFormLabelDescription {
            get {
                return ResourceManager.GetString("ComponentFormLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For calculation?.
        /// </summary>
        public static string ComponentFormLabelForCalculation {
            get {
                return ResourceManager.GetString("ComponentFormLabelForCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ComponentFormLabelName {
            get {
                return ResourceManager.GetString("ComponentFormLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ComponentFormLabelOrder {
            get {
                return ResourceManager.GetString("ComponentFormLabelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of indicator.
        /// </summary>
        public static string ComponentFormLabelType {
            get {
                return ResourceManager.GetString("ComponentFormLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update indicator.
        /// </summary>
        public static string ComponentFormUpdateTitle {
            get {
                return ResourceManager.GetString("ComponentFormUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ComponentTableColumnActions {
            get {
                return ResourceManager.GetString("ComponentTableColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator&apos;s description.
        /// </summary>
        public static string ComponentTableColumnDescription {
            get {
                return ResourceManager.GetString("ComponentTableColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For calculation?.
        /// </summary>
        public static string ComponentTableColumnExpandForCalculation {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandForCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator&apos;s ID.
        /// </summary>
        public static string ComponentTableColumnExpandId {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator&apos;s type.
        /// </summary>
        public static string ComponentTableColumnExpandType {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator&apos;s name.
        /// </summary>
        public static string ComponentTableColumnName {
            get {
                return ResourceManager.GetString("ComponentTableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator&apos;s order.
        /// </summary>
        public static string ComponentTableColumnOrder {
            get {
                return ResourceManager.GetString("ComponentTableColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ComponentTableEditButton {
            get {
                return ResourceManager.GetString("ComponentTableEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sort.
        /// </summary>
        public static string ComponentTableLocaleCancelSort {
            get {
                return ResourceManager.GetString("ComponentTableLocaleCancelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortAlphabetical.
        /// </summary>
        public static string ComponentTableLocaleTriggerAsc {
            get {
                return ResourceManager.GetString("ComponentTableLocaleTriggerAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending alphabetical.
        /// </summary>
        public static string ComponentTableLocaleTriggerDesc {
            get {
                return ResourceManager.GetString("ComponentTableLocaleTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators.
        /// </summary>
        public static string ComponentTableTitle {
            get {
                return ResourceManager.GetString("ComponentTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create indicator.
        /// </summary>
        public static string PageDrawerCreateGroupButton {
            get {
                return ResourceManager.GetString("PageDrawerCreateGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PageMessageCreated {
            get {
                return ResourceManager.GetString("PageMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string PageMessageUpdated {
            get {
                return ResourceManager.GetString("PageMessageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
