//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.TemplatesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.TemplatesResources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionTableDelete {
            get {
                return ResourceManager.GetString("ActionTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template edit.
        /// </summary>
        public static string ActionTableEdit {
            get {
                return ResourceManager.GetString("ActionTableEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft delete.
        /// </summary>
        public static string ActionTableSoftDelete {
            get {
                return ResourceManager.GetString("ActionTableSoftDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearButtonFilter {
            get {
                return ResourceManager.GetString("ClearButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create template.
        /// </summary>
        public static string DrawerCreateTitle {
            get {
                return ResourceManager.GetString("DrawerCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template.
        /// </summary>
        public static string DrawerEditTitle {
            get {
                return ResourceManager.GetString("DrawerEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template.
        /// </summary>
        public static string DrawerShowButton {
            get {
                return ResourceManager.GetString("DrawerShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inut the author Id.
        /// </summary>
        public static string InputAuthorIDPlaceholder {
            get {
                return ResourceManager.GetString("InputAuthorIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonFilter {
            get {
                return ResourceManager.GetString("SearchButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client.
        /// </summary>
        public static string SelectClient {
            get {
                return ResourceManager.GetString("SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template state.
        /// </summary>
        public static string SelectStatePlaceHolder {
            get {
                return ResourceManager.GetString("SelectStatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template type.
        /// </summary>
        public static string SelectTypePlaceholder {
            get {
                return ResourceManager.GetString("SelectTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string TableColumnActions {
            get {
                return ResourceManager.GetString("TableColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TableColumnDescription {
            get {
                return ResourceManager.GetString("TableColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        public static string TableColumnName {
            get {
                return ResourceManager.GetString("TableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TableColumnStatus {
            get {
                return ResourceManager.GetString("TableColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachment?.
        /// </summary>
        public static string TableExpandAllowAttachment {
            get {
                return ResourceManager.GetString("TableExpandAllowAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorID.
        /// </summary>
        public static string TableExpandAuthorID {
            get {
                return ResourceManager.GetString("TableExpandAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation type.
        /// </summary>
        public static string TableExpandCalculationType {
            get {
                return ResourceManager.GetString("TableExpandCalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string TableExpandClientID {
            get {
                return ResourceManager.GetString("TableExpandClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback type.
        /// </summary>
        public static string TableExpandFeedbackType {
            get {
                return ResourceManager.GetString("TableExpandFeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ID.
        /// </summary>
        public static string TableExpandID {
            get {
                return ResourceManager.GetString("TableExpandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is tempalte archived?.
        /// </summary>
        public static string TableExpandIsArchived {
            get {
                return ResourceManager.GetString("TableExpandIsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template type.
        /// </summary>
        public static string TableExpandTemplateType {
            get {
                return ResourceManager.GetString("TableExpandTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sort.
        /// </summary>
        public static string TableLocaleCancelSort {
            get {
                return ResourceManager.GetString("TableLocaleCancelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortAlphabetical.
        /// </summary>
        public static string TableLocaleTriggerAsc {
            get {
                return ResourceManager.GetString("TableLocaleTriggerAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending alphabetical.
        /// </summary>
        public static string TableLocaleTriggerDesc {
            get {
                return ResourceManager.GetString("TableLocaleTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table with templates.
        /// </summary>
        public static string TableTitle {
            get {
                return ResourceManager.GetString("TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template created at.
        /// </summary>
        public static string TemplateExpandCreatedAt {
            get {
                return ResourceManager.GetString("TemplateExpandCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated at.
        /// </summary>
        public static string TemplateExpandUpdatedAt {
            get {
                return ResourceManager.GetString("TemplateExpandUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
