//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.Resources.TemplatesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.Resources.TemplatesResources.TemplateResx", typeof(TemplateResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felete.
        /// </summary>
        public static string ActionTableDelete {
            get {
                return ResourceManager.GetString("ActionTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ActionTableEdit {
            get {
                return ResourceManager.GetString("ActionTableEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftDelete.
        /// </summary>
        public static string ActionTableSoftDelete {
            get {
                return ResourceManager.GetString("ActionTableSoftDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template create.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachment.
        /// </summary>
        public static string CreateTemplateAllowAttachment {
            get {
                return ResourceManager.GetString("CreateTemplateAllowAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        public static string CreateTemplateAuthorID {
            get {
                return ResourceManager.GetString("CreateTemplateAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateTemplateButton {
            get {
                return ResourceManager.GetString("CreateTemplateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation type.
        /// </summary>
        public static string CreateTemplateCalculationType {
            get {
                return ResourceManager.GetString("CreateTemplateCalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateTemplateCancelButton {
            get {
                return ResourceManager.GetString("CreateTemplateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CreateTemplateDescription {
            get {
                return ResourceManager.GetString("CreateTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback type.
        /// </summary>
        public static string CreateTemplateFeedbackType {
            get {
                return ResourceManager.GetString("CreateTemplateFeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateTemplateName {
            get {
                return ResourceManager.GetString("CreateTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client.
        /// </summary>
        public static string CreateTemplateSelectClient {
            get {
                return ResourceManager.GetString("CreateTemplateSelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template type.
        /// </summary>
        public static string CreateTemplateTemplateType {
            get {
                return ResourceManager.GetString("CreateTemplateTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy - MM - dd HH:mm.
        /// </summary>
        public static string DateTimeFormater {
            get {
                return ResourceManager.GetString("DateTimeFormater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create template.
        /// </summary>
        public static string DrawerShowButton {
            get {
                return ResourceManager.GetString("DrawerShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a client.
        /// </summary>
        public static string FilterSelectClient {
            get {
                return ResourceManager.GetString("FilterSelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form isn&apos;t validate.
        /// </summary>
        public static string formNotValidate {
            get {
                return ResourceManager.GetString("formNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        public static string InputAuthorIDPlaceholder {
            get {
                return ResourceManager.GetString("InputAuthorIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template&apos;s filter.
        /// </summary>
        public static string MainDividerFilter {
            get {
                return ResourceManager.GetString("MainDividerFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template&apos;s table.
        /// </summary>
        public static string MainDividerTable {
            get {
                return ResourceManager.GetString("MainDividerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvaluationTemplates.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select template status.
        /// </summary>
        public static string SelectStatusPlaceHolder {
            get {
                return ResourceManager.GetString("SelectStatusPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select template type.
        /// </summary>
        public static string SelectTypePlaceholder {
            get {
                return ResourceManager.GetString("SelectTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string TableColumnControls {
            get {
                return ResourceManager.GetString("TableColumnControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TableColumnDescription {
            get {
                return ResourceManager.GetString("TableColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        public static string TableColumnName {
            get {
                return ResourceManager.GetString("TableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TableColumnStatus {
            get {
                return ResourceManager.GetString("TableColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachment.
        /// </summary>
        public static string TableExpandAllowAttachment {
            get {
                return ResourceManager.GetString("TableExpandAllowAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s ID.
        /// </summary>
        public static string TableExpandAuthorID {
            get {
                return ResourceManager.GetString("TableExpandAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcualtion type.
        /// </summary>
        public static string TableExpandCalculationType {
            get {
                return ResourceManager.GetString("TableExpandCalculationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s ID.
        /// </summary>
        public static string TableExpandClientID {
            get {
                return ResourceManager.GetString("TableExpandClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s name.
        /// </summary>
        public static string TableExpandClientName {
            get {
                return ResourceManager.GetString("TableExpandClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedbackType.
        /// </summary>
        public static string TableExpandFeedbackType {
            get {
                return ResourceManager.GetString("TableExpandFeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ID.
        /// </summary>
        public static string TableExpandID {
            get {
                return ResourceManager.GetString("TableExpandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is archived?.
        /// </summary>
        public static string TableExpandIsArchived {
            get {
                return ResourceManager.GetString("TableExpandIsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template type.
        /// </summary>
        public static string TableExpandTemplateType {
            get {
                return ResourceManager.GetString("TableExpandTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sort.
        /// </summary>
        public static string TableLocaleCancelSort {
            get {
                return ResourceManager.GetString("TableLocaleCancelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortAlphabetical.
        /// </summary>
        public static string TableLocaleTriggerAsc {
            get {
                return ResourceManager.GetString("TableLocaleTriggerAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending alphabetical.
        /// </summary>
        public static string TableLocaleTriggerDesc {
            get {
                return ResourceManager.GetString("TableLocaleTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TableViewButton {
            get {
                return ResourceManager.GetString("TableViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template created at.
        /// </summary>
        public static string TemplateExpandCreatedAt {
            get {
                return ResourceManager.GetString("TemplateExpandCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated at.
        /// </summary>
        public static string TemplateExpandUpdatedAt {
            get {
                return ResourceManager.GetString("TemplateExpandUpdatedAt", resourceCulture);
            }
        }
    }
}
