//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.ClientResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientsPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientsPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.ClientResources.ClientsPages", typeof(ClientsPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComponentFormButtonCancel {
            get {
                return ResourceManager.GetString("ComponentFormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ComponentFormButtonCreate {
            get {
                return ResourceManager.GetString("ComponentFormButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ComponentFormButtonUpdate {
            get {
                return ResourceManager.GetString("ComponentFormButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string ComponentFormCreateTitle {
            get {
                return ResourceManager.GetString("ComponentFormCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the country ID.
        /// </summary>
        public static string ComponentFormLabelCountryID {
            get {
                return ResourceManager.GetString("ComponentFormLabelCountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the new client description.
        /// </summary>
        public static string ComponentFormLabelDescription {
            get {
                return ResourceManager.GetString("ComponentFormLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the new client name.
        /// </summary>
        public static string ComponentFormLabelName {
            get {
                return ResourceManager.GetString("ComponentFormLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the new state for the client.
        /// </summary>
        public static string ComponentFormLabelStatus {
            get {
                return ResourceManager.GetString("ComponentFormLabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Client.
        /// </summary>
        public static string ComponentFormUpdateTitle {
            get {
                return ResourceManager.GetString("ComponentFormUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ComponentTableColumnActions {
            get {
                return ResourceManager.GetString("ComponentTableColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client description.
        /// </summary>
        public static string ComponentTableColumnDescription {
            get {
                return ResourceManager.GetString("ComponentTableColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country  associated.
        /// </summary>
        public static string ComponentTableColumnExpandCountryID {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandCountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client created at.
        /// </summary>
        public static string ComponentTableColumnExpandCreatedAt {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client id.
        /// </summary>
        public static string ComponentTableColumnExpandId {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client updated at.
        /// </summary>
        public static string ComponentTableColumnExpandUpdatedAt {
            get {
                return ResourceManager.GetString("ComponentTableColumnExpandUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        public static string ComponentTableColumnName {
            get {
                return ResourceManager.GetString("ComponentTableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client status.
        /// </summary>
        public static string ComponentTableColumnStatus {
            get {
                return ResourceManager.GetString("ComponentTableColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        public static string ComponentTableEditButton {
            get {
                return ResourceManager.GetString("ComponentTableEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sort.
        /// </summary>
        public static string ComponentTableLocaleCancelSort {
            get {
                return ResourceManager.GetString("ComponentTableLocaleCancelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortAlphabetical.
        /// </summary>
        public static string ComponentTableLocaleTriggerAsc {
            get {
                return ResourceManager.GetString("ComponentTableLocaleTriggerAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending alphabetical.
        /// </summary>
        public static string ComponentTableLocaleTriggerDesc {
            get {
                return ResourceManager.GetString("ComponentTableLocaleTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients list.
        /// </summary>
        public static string ComponentTableTitle {
            get {
                return ResourceManager.GetString("ComponentTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy - MM - dd.
        /// </summary>
        public static string DateFormater {
            get {
                return ResourceManager.GetString("DateFormater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy - MM - dd HH:mm.
        /// </summary>
        public static string DateTimeFormater {
            get {
                return ResourceManager.GetString("DateTimeFormater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string PageDrawerCreateClientButton {
            get {
                return ResourceManager.GetString("PageDrawerCreateClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client created successfully.
        /// </summary>
        public static string PageMessageClientCreated {
            get {
                return ResourceManager.GetString("PageMessageClientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client updated successfully.
        /// </summary>
        public static string PageMessageClientUpdated {
            get {
                return ResourceManager.GetString("PageMessageClientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
