//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.Resources.TemplatesResources.TabQuestions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabQuestionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabQuestionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.Resources.TemplatesResources.TabQuestions.TabQuestionsR" +
                            "esx", typeof(TabQuestionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated group.
        /// </summary>
        public static string AssociatedGroup {
            get {
                return ResourceManager.GetString("AssociatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create question.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create value.
        /// </summary>
        public static string CreateItemValueButton {
            get {
                return ResourceManager.GetString("CreateItemValueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create question item.
        /// </summary>
        public static string CreateQuestionItemButton {
            get {
                return ResourceManager.GetString("CreateQuestionItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of evaluation control.
        /// </summary>
        public static string EvaluationControl {
            get {
                return ResourceManager.GetString("EvaluationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form not validate.
        /// </summary>
        public static string FormNotValid {
            get {
                return ResourceManager.GetString("FormNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify all.
        /// </summary>
        public static string ModifyAllQuestion {
            get {
                return ResourceManager.GetString("ModifyAllQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Question.
        /// </summary>
        public static string TabListCreateQuestionsDivider {
            get {
                return ResourceManager.GetString("TabListCreateQuestionsDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create value for a list.
        /// </summary>
        public static string TabListCreateQuestionsListValueModal {
            get {
                return ResourceManager.GetString("TabListCreateQuestionsListValueModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions list.
        /// </summary>
        public static string TabListQuestionsDivider {
            get {
                return ResourceManager.GetString("TabListQuestionsDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string TabQuestionsTitle {
            get {
                return ResourceManager.GetString("TabQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in update.
        /// </summary>
        public static string UpdateQuestionError {
            get {
                return ResourceManager.GetString("UpdateQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully updated.
        /// </summary>
        public static string UpdateQuestionSuccess {
            get {
                return ResourceManager.GetString("UpdateQuestionSuccess", resourceCulture);
            }
        }
    }
}
