//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.GroupsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupsPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupsPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.GroupsResources.GroupsPages", typeof(GroupsPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComponentFormButtonCancel {
            get {
                return ResourceManager.GetString("ComponentFormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        public static string ComponentFormButtonCreate {
            get {
                return ResourceManager.GetString("ComponentFormButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ComponentFormButtonUpdate {
            get {
                return ResourceManager.GetString("ComponentFormButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string ComponentFormCreateTitle {
            get {
                return ResourceManager.GetString("ComponentFormCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group&apos;s Author ID.
        /// </summary>
        public static string ComponentFormLabelAuthorID {
            get {
                return ResourceManager.GetString("ComponentFormLabelAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group&apos;s description.
        /// </summary>
        public static string ComponentFormLabelDescription {
            get {
                return ResourceManager.GetString("ComponentFormLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group&apos;s name.
        /// </summary>
        public static string ComponentFormLabelName {
            get {
                return ResourceManager.GetString("ComponentFormLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group&apos;s order.
        /// </summary>
        public static string ComponentFormLabelOrder {
            get {
                return ResourceManager.GetString("ComponentFormLabelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parent ID.
        /// </summary>
        public static string ComponentFormLabelParentID {
            get {
                return ResourceManager.GetString("ComponentFormLabelParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select associated template.
        /// </summary>
        public static string ComponentFormSelectTemplate {
            get {
                return ResourceManager.GetString("ComponentFormSelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update group.
        /// </summary>
        public static string ComponentFormUpdateTitle {
            get {
                return ResourceManager.GetString("ComponentFormUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ComponentListEditGroup {
            get {
                return ResourceManager.GetString("ComponentListEditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string ComponentListHeader {
            get {
                return ResourceManager.GetString("ComponentListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string PageDrawerCreateGroupButton {
            get {
                return ResourceManager.GetString("PageDrawerCreateGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group created susscesfully.
        /// </summary>
        public static string PageMessageCreated {
            get {
                return ResourceManager.GetString("PageMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group update successfully.
        /// </summary>
        public static string PageMessageUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PageMessageUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
