//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.Resources.TemplatesResources.TabServicesAndFields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabServicesAndFieldsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabServicesAndFieldsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.Resources.TemplatesResources.TabServicesAndFields.TabSe" +
                            "rvicesAndFieldsResx", typeof(TabServicesAndFieldsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context field values.
        /// </summary>
        public static string ContextFieldsValuesPageTitle {
            get {
                return ResourceManager.GetString("ContextFieldsValuesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View associated values.
        /// </summary>
        public static string ContextFieldsViewContextValues {
            get {
                return ResourceManager.GetString("ContextFieldsViewContextValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new context type.
        /// </summary>
        public static string CreateContextFieldType {
            get {
                return ResourceManager.GetString("CreateContextFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form isn&apos;t validate.
        /// </summary>
        public static string FormNotValid {
            get {
                return ResourceManager.GetString("FormNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated services.
        /// </summary>
        public static string ServicesTransferServiciosAsociados {
            get {
                return ResourceManager.GetString("ServicesTransferServiciosAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalible services.
        /// </summary>
        public static string ServicesTransferServiciosDisponibles {
            get {
                return ResourceManager.GetString("ServicesTransferServiciosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new context type.
        /// </summary>
        public static string TabContextCreateFieldsButon {
            get {
                return ResourceManager.GetString("TabContextCreateFieldsButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context fields types.
        /// </summary>
        public static string TabContextFieldsDivider {
            get {
                return ResourceManager.GetString("TabContextFieldsDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services and fields.
        /// </summary>
        public static string TabServicensAndFieldsTitle {
            get {
                return ResourceManager.GetString("TabServicensAndFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TabServicensDivider {
            get {
                return ResourceManager.GetString("TabServicensDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update context field type.
        /// </summary>
        public static string UpdateContextFieldType {
            get {
                return ResourceManager.GetString("UpdateContextFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLenght.
        /// </summary>
        public static string UpdateMaxLength {
            get {
                return ResourceManager.GetString("UpdateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UpdateName {
            get {
                return ResourceManager.GetString("UpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string UpdateRequired {
            get {
                return ResourceManager.GetString("UpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string UpdateSize {
            get {
                return ResourceManager.GetString("UpdateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string UpdateVisible {
            get {
                return ResourceManager.GetString("UpdateVisible", resourceCulture);
            }
        }
    }
}
