//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityExperienceUI.Local.ServicesResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityExperienceUI.Local.ServicesResources.ServicesPages", typeof(ServicesPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service&apos;s filter.
        /// </summary>
        public static string ComponentFilterTitle {
            get {
                return ResourceManager.GetString("ComponentFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComponentFormButtonCancel {
            get {
                return ResourceManager.GetString("ComponentFormButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ComponentFormButtonCreate {
            get {
                return ResourceManager.GetString("ComponentFormButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ComponentFormButtonUpdate {
            get {
                return ResourceManager.GetString("ComponentFormButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category.
        /// </summary>
        public static string ComponentFormCreateServiceCategoryTitle {
            get {
                return ResourceManager.GetString("ComponentFormCreateServiceCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create service.
        /// </summary>
        public static string ComponentFormCreateServiceTitle {
            get {
                return ResourceManager.GetString("ComponentFormCreateServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author ID.
        /// </summary>
        public static string ComponentFormLabelAuthorID {
            get {
                return ResourceManager.GetString("ComponentFormLabelAuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ComponentFormLabelDescription {
            get {
                return ResourceManager.GetString("ComponentFormLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ComponentFormLabelName {
            get {
                return ResourceManager.GetString("ComponentFormLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type.
        /// </summary>
        public static string ComponentFormLabelOperationType {
            get {
                return ResourceManager.GetString("ComponentFormLabelOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ComponentFormLabelOrder {
            get {
                return ResourceManager.GetString("ComponentFormLabelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type.
        /// </summary>
        public static string ComponentFormLabelServiceType {
            get {
                return ResourceManager.GetString("ComponentFormLabelServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ComponentFormLabelStatus {
            get {
                return ResourceManager.GetString("ComponentFormLabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service&apos;s category.
        /// </summary>
        public static string ComponentFormSelectCategory {
            get {
                return ResourceManager.GetString("ComponentFormSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update service&apos;s category.
        /// </summary>
        public static string ComponentFormUpdateCategoryTitle {
            get {
                return ResourceManager.GetString("ComponentFormUpdateCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update service.
        /// </summary>
        public static string ComponentFormUpdateTitle {
            get {
                return ResourceManager.GetString("ComponentFormUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ComponentListEdit {
            get {
                return ResourceManager.GetString("ComponentListEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services list.
        /// </summary>
        public static string ComponentListHeader {
            get {
                return ResourceManager.GetString("ComponentListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new service category.
        /// </summary>
        public static string PageDrawerCreateCategoryButton {
            get {
                return ResourceManager.GetString("PageDrawerCreateCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new service.
        /// </summary>
        public static string PageDrawerCreateServiceButton {
            get {
                return ResourceManager.GetString("PageDrawerCreateServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string PageDrawerEditCategoryButton {
            get {
                return ResourceManager.GetString("PageDrawerEditCategoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services dosen&apos;t exsist with that category.
        /// </summary>
        public static string PageGetServiceByCategoryDataNull {
            get {
                return ResourceManager.GetString("PageGetServiceByCategoryDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully.
        /// </summary>
        public static string PageMessageCreated {
            get {
                return ResourceManager.GetString("PageMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully update.
        /// </summary>
        public static string PageMessageUpdated {
            get {
                return ResourceManager.GetString("PageMessageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string PageTittle {
            get {
                return ResourceManager.GetString("PageTittle", resourceCulture);
            }
        }
    }
}
